export const SCENE_KEYS = {
  PRELOAD: 'PRELOAD',
  TITLE: 'TITLE',
  GAME: 'GAME',
  TEST: 'TEST',
  MENU: 'MENU',
  SETTING: 'SETTING',
  UI: 'UI'
} as const;

export const ASSET_KEYS = {
  TITLE: 'TITLE',
  CLICK_TO_START: 'CLICK_TO_START',
  CARDS: 'CARDS',
  LILAC_ONE: 'LILAC_ONE',
  LILAC_TWO: 'LILAC_TWO',
  LILAC_THREE: 'LILAC_THERE',
  MP3: 'MP3',
  VINYL: 'VINYL',
  JOURNAL: 'JOURNAL',
  EYE: 'EYE',
  FASTFORWARD: 'FASTFORWARD',
  FILE: 'FILE',
  SAVE: 'SAVE',
  SETTINGS: 'SETTINGS',
  UNDO: 'UNDO',
  DAFFY: 'DAFFY',
  ASTER: 'ASTER',

  AYA_ANGRY: 'AYA_ANGRY', 
  AYA_EWW: 'AYA_EWW',
  AYA_GASP: 'AYA_GASP',
  AYA_NEUTRAL: 'AYA_NEUTRAL',
  AYA_HAPPY: 'AYA_HAPPY',
  AYA_SAD: 'AYA_SAD',
  AYA_SHOCKED: 'AYA_SHOCKED',
  
  KOGA_ANGRY: 'KOGA_ANGRY',
  KOGA_EWW: 'KOGA_EWW',
  KOGA_GASP: 'KOGA_GASP',
  KOGA_NEUTRAL: 'KOGA_NEUTRAL',
  KOGA_HAPPY: 'KOGA_HAPPY',
  KOGA_SAD: 'KOGA_SAD',
  KOGA_SHOCKED: 'KOGA_SHOCKED',


} as const;

export const CARD_WIDTH = 37;
export const CARD_HEIGHT = 52;
